# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 19:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import semillas_backend.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160829_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='User Location, only read in production user admin panel', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to=semillas_backend.users.models.User.user_photo_upload),
        ),
    ]
