# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170119_1047'),
        ('users', '0007_auto_20170226_1801'),
    ]

    operations = [
    ]
