# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-11 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import semillas_backend.users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20170302_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faircoin_address',
            field=models.CharField(blank=True, max_length=36, validators=[semillas_backend.users.validators.is_blockchain_address]),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Telegram Id for peer communication. Example: @username', max_length=60, validators=[semillas_backend.users.validators.starts_with_at]),
        ),
    ]
