# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170811_1638'),
    ]

    operations = [
            migrations.RunSQL(
                "CREATE EXTENSION unaccent;"
                "CREATE TEXT SEARCH CONFIGURATION spanish_unaccent( COPY = spanish );"
                "ALTER TEXT SEARCH CONFIGURATION spanish_unaccent ALTER MAPPING FOR hword, hword_part, word WITH unaccent, spanish_stem;"
                )

    ]
