# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170811_1638'),
    ]

    operations = [
    ]
