# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171011_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_manually_set',
            field=models.BooleanField(default=False, help_text='Flag indicating whether the user has introduced their location or not'),
        ),
    ]
