# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, default=None, help_text='Your website.', null=True, verbose_name='your website'),
        ),
    ]
