# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160928_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the category.', max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Category Picture', null=True, upload_to=services.models.Category.category_photo_upload)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Category'),
        ),
    ]
