# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20161006_2029'),
        ('services', '0003_auto_20161001_1725'),
    ]

    operations = [
    ]
