# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170505_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicephoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, help_text='Photos of the service being offered', max_length=300, null=True, upload_to=services.models.ServicePhoto.service_photo_upload),
        ),
    ]
