# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170617_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='A name for the category.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(help_text='A name for the category.', max_length=100, null=True, unique=True),
        ),
    ]
