# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 08:28
from __future__ import unicode_literals

from django.db import migrations

from services.factory import categories, CategoryFactory

def populate_categories(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model('services', 'Category')
    Category.objects.all().delete()
    for i in range(len(categories)):
        CategoryFactory(name=categories[i], name_es=categories[i], order=i)

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170729_0711'),
    ]

    operations = [
        migrations.RunPython(populate_categories),
    ]
