# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicephoto',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of the post.'),
            preserve_default=False,
        ),
    ]
