FROM python:3.5

ENV PYTHONUNBUFFERED 1

#install geos
RUN cd ~ && wget http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
RUN cd ~ && tar xjf geos-3.4.2.tar.bz2
RUN cd ~/geos-3.4.2 && ./configure && make && make install

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

RUN apt-get update && \
    apt-get install -y gettext && \
    apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
