# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='running_balance',
            new_name='balance_dest',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_source',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Value of the wallet at the time of this transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_dest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_inbound', to='wallet.Wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_source',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_outbound', to='wallet.Wallet'),
            preserve_default=False,
        ),
    ]
