# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='running_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_dest',
            field=models.IntegerField(default=0, help_text='Value of the wallet at the time of this transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_source',
            field=models.IntegerField(blank=True, default=0, help_text='Value of the wallet at the time of this transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_dest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_inbound', to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_source',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_outbound', to='wallet.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(help_text='Available seeds in wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
