# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20170120_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_source',
            field=models.PositiveIntegerField(blank=True, 
                default=0, 
                help_text='Value of the wallet at the time of this transaction'),
        ),
    ]
