# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20170209_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_dest',
            field=models.FloatField(default=0, help_text='Value of the wallet at the time of this transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_source',
            field=models.FloatField(blank=True, default=0, help_text='Value of the wallet at the time of this transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(help_text='Value of the tansaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(help_text='Available seeds in wallet'),
        ),
    ]
