# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20170126_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_dest',
            field=models.IntegerField(default=0, help_text='Value of the wallet at the time of this transaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
