# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='A title for what you offer.', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date of the post.')),
                ('description', models.TextField(help_text='A description of the service.', max_length=2000)),
                ('available', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, default=None, help_text='Your website.', verbose_name='your website')),
                ('seeds_price', models.PositiveIntegerField(help_text='Proposed price in seeds')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
